version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      hardhat:
        patterns:
          - "hardhat"
          - "hardhat-*"
          - "@nomicfoundation/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "typescript-eslint"
          - "@types/eslint__js"
      typescript:
        patterns:
          - "typescript"
          - "ts-node"
          - "@types/*"
        exclude-patterns:
          - "@types/eslint__js"
      viem:
        patterns:
          - "viem"
          - "abitype"
      prettier:
        patterns:
          - "prettier"
      chai:
        patterns:
          - "chai"
          - "@types/chai"
          - "@types/chai-as-promised"
